server:
port: 9090

spring:
datasource:
url: jdbc:mysql://localhost:3306/employeeinfo
username: root
password: Venu12356
driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
database-platform: org.hibernate.dialect.MySQL8Dialect
hibernate:
ddl-auto: update
show-sql: true